///|
pub extend Mode with @debug.Debug::{to_repr}

///|
pub extend Mode with ToJson::{to_json}

///|
pub extend Mode with Eq::{not_equal, equal}

///|
pub extend AtomFamily with @debug.Debug::{to_repr}

///|
pub extend AtomFamily with ToJson::{to_json}

///|
pub extend AtomFamily with Eq::{not_equal, equal}

///|
pub extend Measurement with @debug.Debug::{to_repr}

///|
pub extend Measurement with ToJson::{to_json}

///|
pub extend Measurement with Eq::{not_equal, equal}

///|
pub extend StyleLevel with @debug.Debug::{to_repr}

///|
pub extend StyleLevel with ToJson::{to_json}

///|
pub extend StyleLevel with Eq::{not_equal, equal}

///|
pub extend OperatorContent with @debug.Debug::{to_repr}

///|
pub extend OperatorContent with ToJson::{to_json}

///|
pub extend OperatorContent with Eq::{not_equal, equal}

///|
pub extend LapAlignment with @debug.Debug::{to_repr}

///|
pub extend LapAlignment with ToJson::{to_json}

///|
pub extend LapAlignment with Eq::{not_equal, equal}

///|
pub extend ArrayColumn with @debug.Debug::{to_repr}

///|
pub extend ArrayColumn with ToJson::{to_json}

///|
pub extend ArrayColumn with Eq::{not_equal, equal}

///|
pub extend ColumnSeparationType with @debug.Debug::{to_repr}

///|
pub extend ColumnSeparationType with ToJson::{to_json}

///|
pub extend ColumnSeparationType with Eq::{not_equal, equal}

///|
pub extend ParseNode with @debug.Debug::{to_repr}

///|
pub extend ParseNode with ToJson::{to_json}

///|
pub extend ParseNode with Eq::{not_equal, equal}

///|
pub extend ParseFailure with @debug.Debug::{to_repr}

///|
pub extend ParseFailure with ToJson::{to_json}

///|
pub extend ParseFailure with Eq::{not_equal, equal}

///|
pub extend Diagnostic with @debug.Debug::{to_repr}

///|
pub extend Diagnostic with ToJson::{to_json}

///|
pub extend Diagnostic with Eq::{not_equal, equal}

///|
pub extend SourceLocation with @debug.Debug::{to_repr}

///|
pub extend SourceLocation with ToJson::{to_json}

///|
pub extend SourceLocation with Eq::{not_equal, equal}

///|
pub extend UnicodeScriptKind with Eq::{not_equal, equal}

///|
pub extend Settings with Default::{default}
